#constans.py
DEBUG_MODE = True

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 700
TARGET_RATIO = SCREEN_WIDTH/SCREEN_HEIGHT

PLATFORM_WIDTH = 500
PLATFORM_HEIGHT = 40
VERTICAL_GAP = 100

FPS = 60

TITLE = "Hack Jumper"